### ISSUE TITLE
wyswietlanie wyniku

### ISSUE THREAD

**Issue by michal-bootcamp** [JoannaKu/Java-Script-12#1]
Najpierw podpowiedzi trudniejsze:
1. znajdz w devtoolsach w html `id` elementu, w ktorym powinien wyswietlac sie wynik
2. znajdz w js zmienna, do ktorej przypisywany jest element z tym id
3. sprawdz jaka funkcja aktualizuje ten element przez `.innerHTML`
4. i zobaczysz, ze ta funkcja nigdzie nie jest wywolywana, wiec wywolaj ja w miejscu, w ktorym uwazasz, ze wynik sie zmienil i nalezaloby ten wynik zaktualizowac na widoku

**Comment by JoannaKu** [comment]
skończone, wszystko powinno działać. Zastanawiam się tylko, czy nie da rady jakość skrócić tej ostatniej funkcji, żeby nie trzeba było dwa razy powtarzać komendy:
 gameState = 'ended';
 setGameElements();
?? w inny sposób niż tworzenie osobnej funkcji i jej wywoływać.

**Comment by michal-bootcamp** [comment]
dobrze, ze juz zauwazasz takie rzeczy. Mozna by ja skrocic na tej zasadzie, ze np przed wywolaniem `checkWinner();` sprawdzic czy punkty gracza lub komputera sa rowne 10 i dopiero wywolac te funkcje. Wtedy wewnatrz niej te dwa wspolne warunki moglabys umiescic poza blokiem `if...else`

Popraw jeszcze jedna rzecz - obecnie jak klikam "Jeszcze raz", to wyniki nie sa wyzerowane tylko wyswietlaja sie z poprzedniej rozgrywki poki nie zrobie ruchu

**Comment by JoannaKu** [comment]
poprawione :)
nie zmieniałam tego gameState = 'ended' i setGameElements() bo stwierdziłam, że w sumie na jedno by wyszło. Mam to też zmienić?

**Comment by michal-bootcamp** [comment]
nie, nie zmieniaj - tak jak mowisz na jedno by wyszlo.

A co do Twojej zmiany, to dziala, ale dopisalas cos, co robi juz funkcja `setGamePoints()`, wiec zamiast tej zmiany, proponuje zebys wywolala funkcje `setGamePoints()` wewnatrz funkcji `newGame()`

**Comment by JoannaKu** [comment]
Zrobione. Faktycznie ma to więcej sensu :)

**Comment by michal-bootcamp** [comment]
super :)
